services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.backend  # Dockerfile for backend service
    volumes:
      - ./codelet:/app/src/backend  # Mount the backend source code
    ports:
      - "8080:8080"  # Map container port 8080 to host port 8080
    depends_on:
      - ollama

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend  # Dockerfile for frontend service
    volumes:
      - ./codelet:/app/src/frontend  # Mount the frontend source code
    ports:
      - "3000:3000"  # Map container port 3000 to host port 3000
    depends_on:
      - backend  # Ensure backend is started before frontend

  ollama:
    container_name: ollama
    build:
      context: .
      dockerfile: ./Dockerfile.ollama
    image: ollama
    entrypoint: /tmp/run_ollama.sh
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    stdin_open: true
    tty: true

volumes:
  ollama:
